# Generated by Django 5.1.4 on 2025-03-31 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingocheck',
            old_name='item_id',
            new_name='bingo_item',
        ),
    ]
