# Generated by Django 5.1.4 on 2025-03-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_rename_item_id_bingocheck_bingo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingocheck',
            name='bingo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingoitem'),
        ),
    ]
