# Generated by Django 4.2.15 on 2025-11-14 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarathonEvent",
            fields=[
                ("marathon_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("location_city", models.CharField(max_length=50)),
                ("location_cource", models.CharField(max_length=50)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="MarathonReg",
            fields=[
                ("regis_id", models.AutoField(primary_key=True, serialize=False)),
                ("distance", models.CharField(max_length=10)),
                (
                    "marathon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="marathon.marathonevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
