# Generated by Django 5.1.7 on 2025-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarathonEvent',
            fields=[
                ('marathon_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
