# Generated by Django 5.1.7 on 2025-11-09 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marathonevent',
            old_name='date',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='marathonevent',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
