# Generated by Django 5.1.7 on 2025-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0003_marathonreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathonevent',
            name='marathon_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
