# Generated by Django 4.2.15 on 2025-11-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marathon", "0004_alter_marathonevent_marathon_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="marathonevent",
            name="location_city",
            field=models.CharField(default="seoul", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marathonevent",
            name="location_cource",
            field=models.CharField(default="running cources", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marathonreg",
            name="distance",
            field=models.FloatField(default=42.195),
            preserve_default=False,
        ),
    ]
