# Generated by Django 4.2.15 on 2025-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marathon", "0005_marathonevent_location_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marathonreg",
            name="distance",
            field=models.CharField(max_length=10),
        ),
    ]
