# Generated by Django 5.1.7 on 2025-11-13 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0006_alter_marathonreg_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathonevent',
            name='date_time',
        ),
        migrations.AddField(
            model_name='marathonevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marathonevent',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
