# Generated by Django 5.1.4 on 2025-04-06 07:06

import article.models
import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('main_img', models.ImageField(upload_to=article.models.image_upload_path)),
                ('img_artist', models.CharField(max_length=30)),
                ('bgmusic', models.CharField(max_length=50)),
                ('music_artist', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('pay', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
