# Generated by Django 5.1.7 on 2025-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_img_artist_article_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bgmusic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
