# Generated by Django 4.2.15 on 2026-01-13 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_alter_article_bgmusic_alter_article_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
