# Generated by Django 5.1.7 on 2025-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time_h',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
