# Generated by Django 4.2.15 on 2025-11-20 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0005_record_time_h"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("10K", "10km"),
                            ("HM", "Half Marathon"),
                            ("FM", "Full Marathon"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.DurationField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "심사 중"),
                            ("verified", "인증됨"),
                            ("rejected", "반려됨"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "vidence_url",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format=None,
                        keep_meta=True,
                        quality=-1,
                        scale=None,
                        size=[500, 500],
                        upload_to="record",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="record.racecategory",
                    ),
                ),
                (
                    "runner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("runner", "category")},
            },
        ),
    ]
