# Generated by Django 4.2.15 on 2025-11-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0007_alter_personalrecord_category_delete_racecategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalrecord",
            old_name="vidence_url",
            new_name="evidence_url",
        ),
    ]
