# Generated by Django 4.2.15 on 2025-11-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0008_rename_vidence_url_personalrecord_evidence_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personalrecord",
            unique_together=set(),
        ),
    ]
