# Generated by Django 4.2.15 on 2025-11-20 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0009_alter_personalrecord_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalrecord",
            name="runner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
