# Generated by Django 4.2.15 on 2025-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0010_alter_personalrecord_runner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalrecord",
            name="category",
            field=models.CharField(
                choices=[
                    ("10K", "10km"),
                    ("HM", "Half Marathon"),
                    ("FM", "Full Marathon"),
                ],
                max_length=5,
            ),
        ),
    ]
