# Generated by Django 4.2.15 on 2025-11-20 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0011_alter_personalrecord_category"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personalrecord",
            unique_together={("runner", "category")},
        ),
    ]
