# Generated by Django 4.2.15 on 2025-11-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0012_alter_personalrecord_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalrecord",
            name="event_name",
            field=models.CharField(default="title", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="personalrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "심사중"),
                    ("verified", "인증됨"),
                    ("rejected", "반려됨"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
