# Generated by Django 5.1.7 on 2025-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_personalrecord_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
