# Generated by Django 5.1.7 on 2025-11-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0014_personalrecord_date_personalrecord_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='category',
            field=models.CharField(choices=[('10K', '10km'), ('HM', '하프마라톤'), ('FM', '풀마라톤')], max_length=5),
        ),
    ]
