# Generated by Django 4.2.15 on 2025-12-05 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0016_team_teammember"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "user")},
        ),
    ]
