# Generated by Django 4.2.15 on 2025-12-05 09:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("record", "0017_alter_teammember_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("user", "team")},
        ),
    ]
