# Generated by Django 4.2.15 on 2025-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0018_alter_teammember_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personalrecord",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="personalrecord",
            constraint=models.UniqueConstraint(
                fields=("runner", "category"), name="unique_user_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammember",
            constraint=models.UniqueConstraint(
                fields=("user", "team"), name="unique_user_team"
            ),
        ),
    ]
